name: CI

on:
  pull_request:
    branches:
      - master

permissions:
  contents: read

jobs:
  ci-passed:
    name: CI Passed
    runs-on: ubuntu-latest

    steps:
      - name: Mark CI as passed
        run: |
          # This status is intentionally always green for pull requests.
          true
